### ISSUE TITLE
pip3 install frankAllSkyCam doesn't create the directory for frankAllSkyCam

### ISSUE THREAD

**Issue by wooac** [sferlix/frankAllSkyCam#9]
root@allsky:/home/woo# pip3 install frankAllSkyCam
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting frankAllSkyCam
  Downloading https://www.piwheels.org/simple/frankallskycam/frankAllSkyCam-8.4-py3-none-any.whl (28 kB)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from frankAllSkyCam) (1.19.5)
Collecting pytz
  Downloading https://www.piwheels.org/simple/pytz/pytz-2023.3-py3-none-any.whl (502 kB)
     |████████████████████████████████| 502 kB 188 kB/s
Collecting pandas
  Downloading https://www.piwheels.org/simple/pandas/pandas-2.0.2-cp39-cp39-linux_armv7l.whl (38.7 MB)
     |████████████████████████████████| 38.7 MB 39 kB/s
Collecting numpy
  Downloading https://www.piwheels.org/simple/numpy/numpy-1.25.0-cp39-cp39-linux_armv7l.whl (12.5 MB)
     |████████████████████████████████| 12.5 MB 107 kB/s
Collecting python-dateutil>=2.8.2
  Downloading https://www.piwheels.org/simple/python-dateutil/python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 189 kB/s
Collecting tzdata>=2022.1
  Downloading https://www.piwheels.org/simple/tzdata/tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     |████████████████████████████████| 341 kB 283 kB/s
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->frankAllSkyCam) (1.16.0)
Installing collected packages: tzdata, pytz, python-dateutil, numpy, pandas, frankAllSkyCam
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Not uninstalling python-dateutil at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'python-dateutil'. No files were found to uninstall.
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'numpy'. No files were found to uninstall.
Successfully installed frankAllSkyCam-8.4 numpy-1.25.0 pandas-2.0.2 python-dateutil-2.8.2 pytz-2023.3 tzdata-2023.3
root@allsky:/home/woo# ls
Bookshelf  Desktop  Documents  Downloads  Music  Pictures  Public  Templates  test.jpg  Videos

**Comment by sferlix** [comment]
Hi,

the directories, the config.txt, and other files, will be created at the
1st execution, not during the install.

so please after installation run

python3 -m frankAllSkyCam

don't care about errors not related to folder creation.
 then, check the folders and config.txt

hth
frank

Il ven 23 giu 2023, 05:40 Alex Woo ***@***.***> ha scritto:

**Comment by wooac** [comment]
Thanks.   I already switched to thomasjacquin version.

**Comment by sferlix** [comment]
Thanks for raising the issue as I understood that I need to improve the
instructions.

bye


Il ven 23 giu 2023, 07:44 Alex Woo ***@***.***> ha scritto:

> Thanks. I already switched to thomasjacquin version.
>

**Comment by sferlix** [comment]
to generate the folders and config.txt file, you need to run the command: 
`python3 -m frankAllSkyCam`

Readme.md has been improved, making it more clear.
